apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.ghost.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ghost.storage }}