apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.mariadb.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.storage }}