apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-db
  template:
    metadata:
      labels:
        app: ghost-db
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          args:
            - "--transaction-isolation=READ-COMMITTED"
            - "--binlog-format=ROW"
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: ghost
            - name: MARIADB_USER
              value: ghost
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mariadb-password
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mariadb-root-password
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: ghost-db