apiVersion: v1
kind: Secret
metadata:
  name: ghost-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mariadb-password: {{ .Values.secrets.mariadbPassword | quote }}
  mariadb-root-password: {{ .Values.secrets.mariadbRootPassword | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | quote }}