apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aCiDcHaOZ/k3s_argo_homelab.git
    targetRevision: main
    path: apps/semaphore
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
