apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.onlionel.com/lionel/k3s_gitops.git
    targetRevision: main
    path: apps/zabbix
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true