apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SEMAPHORE_ADMIN: {{ .Values.semaphore.admin.username | quote }}
  SEMAPHORE_ADMIN_PASSWORD: {{ .Values.semaphore.admin.password | quote }}
  SEMAPHORE_ADMIN_NAME: {{ .Values.semaphore.admin.name | quote }}
  SEMAPHORE_ADMIN_EMAIL: {{ .Values.semaphore.admin.email | quote }}
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: {{ .Values.semaphore.accessKeyEncryption | quote }}