gitea:
  config:
    server:
      ROOT_URL: https://git.onlionel.com
      DOMAIN: git.onlionel.com
      SSH_DOMAIN: git.onlionel.com
      PROTOCOL: http
      HTTP_PORT: 3000

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: git.onlionel.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
